#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const os = require("os");

// --- Config ---
const PROJECTS_DIR = path.join(os.homedir(), ".claude", "projects");
const TIMEZONE = "Asia/Seoul";

// --- Cleaning ---

/** 메시지 통째 제거 판정용 접두사 */
const DROP_PREFIXES = [
  "This session is being continued from a previous conversation",
  "Base directory for this skill:",
  "Caveat: The messages below were generated by the user while running local commands",
];

function cleanText(raw) {
  let t = raw;

  // 1. 내용 통째 제거 (태그 + 내용)
  t = t.replace(/<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g, "");
  t = t.replace(/<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g, "");
  t = t.replace(/<local-command-stderr>[\s\S]*?<\/local-command-stderr>/g, "");
  t = t.replace(/<teammate-message[\s\S]*?<\/teammate-message>/g, "");
  t = t.replace(/<task-notification>[\s\S]*?<\/task-notification>/g, "");
  t = t.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, "");
  t = t.replace(/<!--[\s\S]*?-->/g, "");

  // 2. 태그만 제거, 내용 보존
  t = t.replace(/<\/?command-name>/g, "");
  t = t.replace(/<\/?command-message>/g, "");
  t = t.replace(/<\/?command-args>/g, "");

  // 3. 후처리
  t = t.replace(/\n{3,}/g, "\n\n").trim();

  return t;
}

/**
 * 클리닝 후 메시지를 통째 제거해야 하는지 판정.
 * null을 반환하면 제거, 문자열을 반환하면 유지.
 */
function processMessage(raw) {
  const cleaned = cleanText(raw);
  for (const prefix of DROP_PREFIXES) {
    if (cleaned.startsWith(prefix)) return null;
  }
  return cleaned;
}

// --- JSONL Parsing ---

function extractUserText(obj) {
  const msg = obj.message;
  if (typeof msg === "string") return msg;
  if (msg && msg.content) {
    if (typeof msg.content === "string") return msg.content;
    if (Array.isArray(msg.content)) {
      const t = msg.content.find((c) => c.type === "text");
      if (t) return t.text;
    }
  }
  return "";
}

function parseSession(filepath) {
  const lines = fs.readFileSync(filepath, "utf-8").split("\n").filter(Boolean);
  let firstTime = null;
  let lastTime = null;
  const messages = [];
  let index = 0;

  for (const line of lines) {
    let obj;
    try {
      obj = JSON.parse(line);
    } catch {
      continue;
    }

    if (obj.timestamp) {
      if (!firstTime) firstTime = obj.timestamp;
      lastTime = obj.timestamp;
    }

    if (obj.type === "user") {
      index++;
      const raw = extractUserText(obj);
      const cleaned = processMessage(raw);
      if (cleaned === null) continue; // 메시지 통째 제거

      const ts = obj.timestamp
        ? new Date(obj.timestamp).toLocaleTimeString("ko-KR", {
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
            hour12: false,
            timeZone: TIMEZONE,
          })
        : "";

      messages.push({ index, time: ts, text: cleaned });
    }
  }

  if (!firstTime) return null;

  const start = new Date(firstTime);
  const end = new Date(lastTime);
  const durationMin = Math.round((end - start) / 1000 / 60);

  const fmt = (d) =>
    d.toLocaleTimeString("ko-KR", {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hour12: false,
      timeZone: TIMEZONE,
    });

  const dateStr = start
    .toLocaleDateString("ko-KR", { timeZone: TIMEZONE, year: "numeric", month: "2-digit", day: "2-digit" })
    .replace(/\. /g, "-")
    .replace(/\./g, "");

  return {
    start_time: fmt(start),
    end_time: fmt(end),
    date: dateStr,
    duration_min: durationMin,
    message_count: messages.length,
    messages,
  };
}

// --- Project Key ---

function toProjectKey(dirname) {
  // C--Users-Langdy-3-WebstormProjects-main → WebstormProjects/main
  // C--Users-Langdy-3-workspace-langdy-langdy-admin → workspace/langdy/langdy-admin
  // 사용자명에 하이픈이 포함될 수 있으므로 알려진 루트 경로 기준으로 자른다
  const roots = ["WebstormProjects", "workspace"];
  // .claude 특수 처리: C--Users-Langdy-3--claude-xxx → .claude/xxx
  if (dirname.includes("--claude")) {
    const idx = dirname.indexOf("--claude");
    return "." + dirname.slice(idx + 1).replace(/-/g, "/");
  }
  for (const root of roots) {
    const idx = dirname.indexOf(root);
    if (idx !== -1) {
      return dirname.slice(idx).replace(/-/g, "/");
    }
  }
  // fallback: C--Users-XXX- 패턴 제거
  let key = dirname.replace(/^C--Users-.*?-(WebstormProjects|workspace)/, "$1").replace(/-/g, "/");
  return key || dirname;
}

// --- Commands ---

function cmdProjects() {
  const dirs = fs.readdirSync(PROJECTS_DIR).filter((d) => {
    try {
      return fs.statSync(path.join(PROJECTS_DIR, d)).isDirectory();
    } catch {
      return false;
    }
  });

  const results = [];
  for (const d of dirs) {
    const full = path.join(PROJECTS_DIR, d);
    const jsonls = fs.readdirSync(full).filter((f) => f.endsWith(".jsonl"));
    if (jsonls.length === 0) continue;

    const latest = jsonls
      .map((f) => fs.statSync(path.join(full, f)).mtime)
      .sort((a, b) => b - a)[0];

    results.push({
      key: toProjectKey(d),
      path: d,
      sessions: jsonls.length,
      last_active: latest.toISOString().slice(0, 10),
    });
  }

  results.sort((a, b) => b.sessions - a.sessions);
  console.log(JSON.stringify(results, null, 2));
}

function findProjectDir(query) {
  const dirs = fs.readdirSync(PROJECTS_DIR).filter((d) => {
    try {
      return fs.statSync(path.join(PROJECTS_DIR, d)).isDirectory();
    } catch {
      return false;
    }
  });

  // 1. key 끝부분 완전 일치 우선
  const exact = dirs.find((d) => {
    const key = toProjectKey(d);
    const segments = key.split("/");
    return segments[segments.length - 1] === query || key.endsWith("/" + query) || key === query;
  });
  if (exact) return exact;

  // 2. 부분 일치
  const matches = dirs.filter((d) => toProjectKey(d).includes(query));

  if (matches.length === 0) {
    console.error(`No project matching "${query}"`);
    process.exit(1);
  }
  if (matches.length > 1) {
    console.error(`Multiple projects match "${query}":`);
    matches.forEach((m) => console.error(`  - ${toProjectKey(m)}`));
    process.exit(1);
  }
  return matches[0];
}

function cmdSessions(query) {
  const dir = findProjectDir(query);
  const full = path.join(PROJECTS_DIR, dir);
  const jsonls = fs.readdirSync(full).filter((f) => f.endsWith(".jsonl"));

  const results = [];
  for (const f of jsonls) {
    const filepath = path.join(full, f);
    const parsed = parseSession(filepath);
    if (!parsed) continue;

    const firstMsg =
      parsed.messages.find((m) => m.text.length > 0)?.text.slice(0, 80) || "";

    results.push({
      session_id: f.replace(".jsonl", "").slice(0, 8),
      date: parsed.date,
      start: parsed.start_time,
      end: parsed.end_time,
      duration_min: parsed.duration_min,
      message_count: parsed.message_count,
      first_message: firstMsg,
    });
  }

  results.sort((a, b) => a.date.localeCompare(b.date) || a.start.localeCompare(b.start));
  console.log(JSON.stringify(results, null, 2));
}

function cmdDetail(sessionId) {
  // 모든 프로젝트에서 session ID로 검색
  const dirs = fs.readdirSync(PROJECTS_DIR).filter((d) => {
    try {
      return fs.statSync(path.join(PROJECTS_DIR, d)).isDirectory();
    } catch {
      return false;
    }
  });

  for (const d of dirs) {
    const full = path.join(PROJECTS_DIR, d);
    const jsonls = fs.readdirSync(full).filter((f) => f.endsWith(".jsonl"));
    const match = jsonls.find((f) => f.startsWith(sessionId));
    if (match) {
      const parsed = parseSession(path.join(full, match));
      if (!parsed) {
        console.error("Session has no data");
        process.exit(1);
      }

      const result = {
        session_id: match.replace(".jsonl", "").slice(0, 8),
        project: toProjectKey(d),
        date: parsed.date,
        start: parsed.start_time,
        end: parsed.end_time,
        duration_min: parsed.duration_min,
        message_count: parsed.message_count,
        messages: parsed.messages,
      };

      console.log(JSON.stringify(result, null, 2));
      return;
    }
  }

  console.error(`Session "${sessionId}" not found`);
  process.exit(1);
}

// --- Main ---

const [, , command, ...args] = process.argv;

switch (command) {
  case "projects":
    cmdProjects();
    break;
  case "sessions":
    if (!args[0]) {
      console.error("Usage: kpi.js sessions <project>");
      process.exit(1);
    }
    cmdSessions(args[0]);
    break;
  case "detail":
    if (!args[0]) {
      console.error("Usage: kpi.js detail <session-id>");
      process.exit(1);
    }
    cmdDetail(args[0]);
    break;
  default:
    console.error("Usage: kpi.js <projects|sessions|detail> [args]");
    process.exit(1);
}
