const childProcess = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const CATEGORIES = ['rules', 'contexts', 'hooks'];
const LEGACY_CATEGORIES = ['agents'];
const SKILLS_PRESERVE = new Set([
  '.system',
  'vercel-composition-patterns',
  'vercel-react-best-practices',
  'web-design-guidelines',
]);

const { buildHooks } = require('./settings-projection');

const repoDir = path.resolve(__dirname, '..');
const sourceDir = path.join(repoDir, 'deploy');
const baseSettingsSource = path.join(sourceDir, 'base-settings.json');
// 직접 복사하지 않고 settings 생성의 재료로만 쓰는 root 파일들.
// base-settings.json(공통 hook)과 타겟별 override(claude/gemini-settings.json).
const SOURCE_ONLY_ROOT_FILES = new Set(['base-settings.json', 'claude-settings.json', 'gemini-settings.json']);

// 각 타겟 설정 = base에서 만든 것(hook) + 타겟 override 파일. override가 우선(키 충돌 시 덮어씀).
function loadBaseSettings() {
  if (!fs.existsSync(baseSettingsSource) || !fs.statSync(baseSettingsSource).isFile()) {
    throw new Error(`base-settings.json을 찾을 수 없습니다: ${baseSettingsSource}`);
  }
  return readJson(baseSettingsSource);
}

// 타겟 override 파일(없으면 {}). base 재료를 덮어쓰는 타겟 전용 설정.
function loadOverride(name) {
  const overridePath = path.join(sourceDir, name);
  return fs.existsSync(overridePath) && fs.statSync(overridePath).isFile() ? readJson(overridePath) : {};
}

function claudeSettingsObject() {
  return { hooks: buildHooks(loadBaseSettings().hooks, 'claude'), ...loadOverride('claude-settings.json') };
}

function geminiSettingsObject() {
  // gemini는 hook 런타임이 없어 base hook을 받지 않는다. override 파일만(현재 없음 → {}).
  return { ...loadOverride('gemini-settings.json') };
}

function codexHooksObject() {
  return { hooks: buildHooks(loadBaseSettings().hooks, 'codex') };
}

function defaultClaudeDir() {
  return path.join(os.homedir(), '.claude');
}

function defaultCodexDir() {
  return path.join(os.homedir(), '.codex');
}

function defaultGeminiDir() {
  return path.join(os.homedir(), '.gemini');
}

function resolveUserPath(input) {
  if (!input || input === '~') return os.homedir();
  if (input.startsWith(`~${path.sep}`) || input.startsWith('~/') || input.startsWith('~\\')) {
    return path.join(os.homedir(), input.slice(2));
  }
  return path.resolve(input);
}

function ensureDeploySource() {
  if (!fs.existsSync(sourceDir) || !fs.statSync(sourceDir).isDirectory()) {
    throw new Error(`Deploy source not found: ${sourceDir}`);
  }
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function removePath(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

function copyPath(src, dest) {
  removePath(dest);
  ensureDir(path.dirname(dest));
  fs.cpSync(src, dest, { recursive: true, force: true, errorOnExist: false });
}

function readJson(file) {
  const raw = fs.readFileSync(file, 'utf8').trim();
  return raw ? JSON.parse(raw) : {};
}

function writeJson(file, value) {
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function buildAgentsContent(targetFileName) {
  const sections = [
    {
      title: 'Global Instructions',
      file: path.join(sourceDir, 'CLAUDE.md'),
    },
  ];

  const rulesDir = path.join(sourceDir, 'rules');
  if (fs.existsSync(rulesDir) && fs.statSync(rulesDir).isDirectory()) {
    const files = fs.readdirSync(rulesDir)
      .filter((file) => file.endsWith('.md'))
      .sort((a, b) => a.localeCompare(b));

    for (const file of files) {
      const title = file === 'global.md' ? 'Global Rules' : `Global Rules - ${path.basename(file, '.md').toUpperCase()}`;
      sections.push({
        title,
        file: path.join(rulesDir, file),
      });
    }
  }

  const body = sections
    .filter((section) => fs.existsSync(section.file) && fs.statSync(section.file).isFile())
    .map((section) => {
      const relativePath = path.relative(sourceDir, section.file).replace(/\\/g, '/');
      const content = fs.readFileSync(section.file, 'utf8').trim();
      return `# ${section.title}\n\n<!-- Source: deploy/${relativePath} -->\n\n${content}`;
    })
    .join('\n\n---\n\n');

  const lowerName = path.basename(targetFileName, '.md').toLowerCase();
  return `<!-- Generated by ai-contexts npm run sync:system. Do not edit ~/.${lowerName}/${targetFileName} directly. -->\n\n${body}\n`;
}

function buildCodexAgentsContent() {
  return buildAgentsContent('AGENTS.md');
}

function buildGeminiAgentsContent() {
  return buildAgentsContent('GEMINI.md');
}

// 머지된 settings.json 옆에 AC가 넣은 top-level 키 목록을 기록하는 사이드카.
// 다음 sync에서 "지난번엔 AC가 넣었지만 이번 소스엔 없는 키"(고아)를 식별해 제거하는 데 쓴다.
// mergeSettings는 소스 키를 추가만 하므로, 이 매니페스트 없이는 소스에서 사라진 키가 영영 잔존한다.
function settingsManifestPath(targetPath) {
  return path.join(path.dirname(targetPath), `.${path.basename(targetPath)}.ac-keys`);
}

function readManagedKeys(targetPath) {
  const manifestPath = settingsManifestPath(targetPath);
  if (!fs.existsSync(manifestPath)) return [];
  try {
    const parsed = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function mergeSettings(deploy, targetPath) {
  const deployKeys = Object.keys(deploy);
  const existing = fs.existsSync(targetPath) ? readJson(targetPath) : {};

  // 지난 sync에서 AC가 넣었지만 이번 소스엔 없는 top-level 키(고아)를 제거한다.
  for (const key of readManagedKeys(targetPath)) {
    if (!deployKeys.includes(key)) delete existing[key];
  }

  writeJson(targetPath, { ...existing, ...deploy });
  fs.writeFileSync(settingsManifestPath(targetPath), `${JSON.stringify(deployKeys)}\n`, 'utf8');
}

function splitSettings(deploy, targetPath) {
  if (!fs.existsSync(targetPath)) {
    const manifestPath = settingsManifestPath(targetPath);
    if (fs.existsSync(manifestPath)) removePath(manifestPath);
    return false;
  }

  const existing = readJson(targetPath);
  // 현재 소스 키 + 지난 AC 관리 키(고아)를 모두 제거한다.
  const keysToRemove = new Set([...Object.keys(deploy), ...readManagedKeys(targetPath)]);
  for (const key of keysToRemove) {
    delete existing[key];
  }

  const manifestPath = settingsManifestPath(targetPath);
  if (fs.existsSync(manifestPath)) removePath(manifestPath);

  if (Object.keys(existing).length === 0) {
    removePath(targetPath);
  } else {
    writeJson(targetPath, existing);
  }
  return true;
}

function verifySettings(deploy, targetPath) {
  if (!fs.existsSync(targetPath)) return false;

  const target = readJson(targetPath);
  return Object.keys(deploy).every((key) => stableJson(deploy[key]) === stableJson(target[key]));
}

// whole-file 타겟(codex hooks.json)용: 부분키 비교가 아니라 전체 일치를 본다.
function verifyJsonExact(expected, targetPath) {
  if (!fs.existsSync(targetPath)) return false;
  return stableJson(readJson(targetPath)) === stableJson(expected);
}

function stableJson(value) {
  return JSON.stringify(value);
}

function listEntries(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
}

function comparePaths(left, right) {
  if (!fs.existsSync(left) || !fs.existsSync(right)) return false;

  const leftStat = fs.statSync(left);
  const rightStat = fs.statSync(right);
  if (leftStat.isDirectory() !== rightStat.isDirectory()) return false;

  if (leftStat.isDirectory()) {
    const leftEntries = listEntries(left);
    const rightEntries = listEntries(right);
    if (leftEntries.length !== rightEntries.length) return false;

    for (let i = 0; i < leftEntries.length; i += 1) {
      if (leftEntries[i].name !== rightEntries[i].name) return false;
      if (!comparePaths(path.join(left, leftEntries[i].name), path.join(right, rightEntries[i].name))) {
        return false;
      }
    }
    return true;
  }

  return fs.readFileSync(left).equals(fs.readFileSync(right));
}

function deployRootFiles(targetDir, log) {
  let copied = 0;
  for (const entry of listEntries(sourceDir)) {
    if (!entry.isFile()) continue;
    if (SOURCE_ONLY_ROOT_FILES.has(entry.name)) continue;

    const src = path.join(sourceDir, entry.name);
    const dest = path.join(targetDir, entry.name);
    copyPath(src, dest);
    log(`  COPY  ${entry.name}`);
    copied += 1;
  }

  mergeSettings(claudeSettingsObject(), path.join(targetDir, 'settings.json'));
  log('  MERGE settings.json');
  copied += 1;
  return copied;
}

function deploySkills(targetDir, log) {
  const srcSkills = path.join(sourceDir, 'skills');
  if (!fs.existsSync(srcSkills) || !fs.statSync(srcSkills).isDirectory()) return 0;

  const targetSkills = path.join(targetDir, 'skills');
  ensureDir(targetSkills);

  let copied = 0;
  for (const entry of listEntries(srcSkills)) {
    const src = path.join(srcSkills, entry.name);
    copyPath(src, path.join(targetSkills, entry.name));
    log(`  COPY  skills/${entry.name}`);
    copied += 1;
  }
  return copied;
}

function uninstallSkills(targetDir, log) {
  const skillsDir = path.join(targetDir, 'skills');
  let removed = 0;
  for (const entry of listEntries(skillsDir)) {
    if (SKILLS_PRESERVE.has(entry.name)) continue;

    removePath(path.join(skillsDir, entry.name));
    log(`  DEL   skills/${entry.name}`);
    removed += 1;
  }
  return removed;
}

function deployCodexGlobals(targetDir, log = console.log) {
  ensureDir(targetDir);
  uninstallCodexGlobals(targetDir, log);

  let copied = 0;
  const srcContexts = path.join(sourceDir, 'contexts');
  if (fs.existsSync(srcContexts) && fs.statSync(srcContexts).isDirectory()) {
    copyPath(srcContexts, path.join(targetDir, 'contexts'));
    log('  COPY  contexts/');
    copied += 1;
  }

  const srcHooks = path.join(sourceDir, 'hooks');
  if (fs.existsSync(srcHooks) && fs.statSync(srcHooks).isDirectory()) {
    copyPath(srcHooks, path.join(targetDir, 'hooks'));
    log('  COPY  hooks/');
    copied += 1;
  }

  writeJson(path.join(targetDir, 'hooks.json'), codexHooksObject());
  log('  WRITE hooks.json');
  copied += 1;

  fs.writeFileSync(path.join(targetDir, 'AGENTS.md'), buildCodexAgentsContent(), 'utf8');
  log('  WRITE AGENTS.md');
  copied += 1;

  copied += deploySkills(targetDir, log);
  return copied;
}

function deployGeminiGlobals(targetDir, log = console.log) {
  ensureDir(targetDir);
  uninstallGeminiGlobals(targetDir, log);

  let copied = 0;
  const srcContexts = path.join(sourceDir, 'contexts');
  if (fs.existsSync(srcContexts) && fs.statSync(srcContexts).isDirectory()) {
    copyPath(srcContexts, path.join(targetDir, 'contexts'));
    log('  COPY  contexts/');
    copied += 1;
  }

  // gemini(Antigravity CLI)는 hook 러너가 없어 hook을 발동하지 못한다. hook 본문을
  // ~/.gemini/hooks/로 복사하지 않는다 (러너 없는 dead artifact 방지).

  fs.writeFileSync(path.join(targetDir, 'GEMINI.md'), buildGeminiAgentsContent(), 'utf8');
  log('  WRITE GEMINI.md');
  copied += 1;

  copied += deploySkills(targetDir, log);

  mergeSettings(geminiSettingsObject(), path.join(targetDir, 'settings.json'));
  log('  MERGE settings.json');
  copied += 1;

  return copied;
}

function uninstallGeminiGlobals(targetDir, log = console.log) {
  let removed = 0;
  const contextsDir = path.join(targetDir, 'contexts');
  if (fs.existsSync(contextsDir) && fs.statSync(contextsDir).isDirectory()) {
    removePath(contextsDir);
    log('  DEL   contexts/');
    removed += 1;
  }
  const hooksDir = path.join(targetDir, 'hooks');
  if (fs.existsSync(hooksDir) && fs.statSync(hooksDir).isDirectory()) {
    removePath(hooksDir);
    log('  DEL   hooks/');
    removed += 1;
  }
  const geminiFile = path.join(targetDir, 'GEMINI.md');
  if (fs.existsSync(geminiFile) && fs.statSync(geminiFile).isFile()) {
    removePath(geminiFile);
    log('  DEL   GEMINI.md');
    removed += 1;
  }
  {
    const target = path.join(targetDir, 'settings.json');
    if (splitSettings(geminiSettingsObject(), target)) {
      log('  SPLIT settings.json');
      removed += 1;
    }
  }

  removed += uninstallSkills(targetDir, log);
  return removed;
}

async function trustCodexHooks(targetDir, log = console.log, cwd = repoDir) {
  const hooksConfig = path.join(targetDir, 'hooks.json');
  if (!fs.existsSync(hooksConfig) || !fs.statSync(hooksConfig).isFile()) return 0;

  const response = await runCodexAppServer([
    { method: 'hooks/list', params: { cwds: [cwd] } },
  ]);
  const listResult = response.find((message) => Array.isArray(message?.result?.data))?.result;
  const hooks = listResult?.data?.flatMap((entry) => entry.hooks || []) || [];
  const deployedHooks = hooks.filter((hook) => path.resolve(hook.sourcePath || '') === path.resolve(hooksConfig));

  const state = {};
  for (const hook of deployedHooks) {
    if (!hook.key || !hook.currentHash || hook.isManaged) continue;
    state[hook.key] = {
      enabled: true,
      trusted_hash: hook.currentHash,
    };
  }

  if (Object.keys(state).length === 0) return 0;

  await runCodexAppServer([
    {
      method: 'config/batchWrite',
      params: {
        edits: [
          {
            keyPath: 'hooks.state',
            value: state,
            mergeStrategy: 'upsert',
          },
        ],
        reloadUserConfig: true,
      },
    },
  ]);

  log(`  TRUST hooks.state (${Object.keys(state).length})`);
  return Object.keys(state).length;
}

function resolveCodexCli() {
  const explicit = process.env.CODEX_CLI;
  if (explicit && isRunnableCodexCli(explicit)) return explicit;

  const pathHit = findOnPath(process.platform === 'win32' ? ['codex.exe', 'codex.cmd', 'codex.bat', 'codex'] : ['codex']);
  if (pathHit) return pathHit;

  if (process.platform === 'win32') {
    const candidates = [
      path.join(os.homedir(), 'AppData', 'Local', 'OpenAI', 'Codex', 'bin', 'codex.exe'),
      path.join(process.env.LOCALAPPDATA || '', 'OpenAI', 'Codex', 'bin', 'codex.exe'),
      ...findLocalAppCodexBins(),
      ...findWindowsAppCodexBins(),
    ];
    return candidates.find(isRunnableCodexCli) || null;
  }

  return null;
}

function findOnPath(names) {
  const pathValue = process.env.PATH || '';
  const dirs = pathValue.split(path.delimiter).filter(Boolean);
  for (const dir of dirs) {
    for (const name of names) {
      const candidate = path.join(dir, name);
      if (isRunnableCodexCli(candidate)) return candidate;
    }
  }
  return null;
}

function findLocalAppCodexBins() {
  const roots = [
    path.join(os.homedir(), 'AppData', 'Local', 'OpenAI', 'Codex', 'bin'),
    path.join(process.env.LOCALAPPDATA || '', 'OpenAI', 'Codex', 'bin'),
  ];
  const candidates = [];

  for (const root of [...new Set(roots)]) {
    if (!root || !fs.existsSync(root) || !fs.statSync(root).isDirectory()) continue;

    for (const entry of fs.readdirSync(root)) {
      const entryPath = path.join(root, entry);
      try {
        if (fs.statSync(entryPath).isDirectory()) {
          candidates.push(path.join(entryPath, 'codex.exe'));
        }
      } catch {
        // Ignore stale package directories while scanning Desktop-managed bins.
      }
    }
  }

  return candidates.sort((left, right) => {
    try {
      return fs.statSync(right).mtimeMs - fs.statSync(left).mtimeMs;
    } catch {
      return 0;
    }
  });
}

function findWindowsAppCodexBins() {
  const windowsApps = path.join(process.env.ProgramFiles || 'C:\\Program Files', 'WindowsApps');
  if (!fs.existsSync(windowsApps) || !fs.statSync(windowsApps).isDirectory()) return [];

  try {
    return fs.readdirSync(windowsApps)
      .filter((entry) => entry.startsWith('OpenAI.Codex_'))
      .flatMap((entry) => [
        path.join(windowsApps, entry, 'app', 'resources', 'codex.exe'),
        path.join(windowsApps, entry, 'app', 'resources', 'codex'),
      ]);
  } catch {
    return [];
  }
}

function isExecutableFile(file) {
  if (!file) return false;
  try {
    return fs.existsSync(file) && fs.statSync(file).isFile();
  } catch {
    return false;
  }
}

function isRunnableCodexCli(file) {
  if (!isExecutableFile(file)) return false;

  const result = childProcess.spawnSync(file, ['--version'], {
    stdio: 'ignore',
    timeout: 5000,
    windowsHide: true,
  });

  return !result.error && result.status === 0;
}

function runCodexAppServer(requests, options = {}) {
  const cwd = options.cwd || repoDir;
  return new Promise((resolve, reject) => {
    const codexCli = resolveCodexCli();
    if (!codexCli) {
      reject(new Error(
        'Codex CLI not found. Install Codex Desktop/CLI, add codex to PATH, or set CODEX_CLI to the codex executable path.'
      ));
      return;
    }

    const child = childProcess.spawn(codexCli, ['app-server', '--listen', 'stdio://'], {
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    const results = [];
    const pending = new Map();
    let nextId = 1;
    let stderr = '';
    let settled = false;

    const timeout = setTimeout(() => {
      finish(new Error('codex app-server timed out'));
    }, options.timeoutMs || 30000);

    function finish(error) {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      child.kill();
      if (error) {
        if (stderr.trim()) error.message += `\n${stderr.trim()}`;
        reject(error);
      } else {
        resolve(results);
      }
    }

    function send(method, params) {
      const id = nextId;
      nextId += 1;
      pending.set(id, results.length);
      results.push(null);
      child.stdin.write(`${JSON.stringify({ id, method, params })}\n`);
    }

    child.stdout.setEncoding('utf8');
    child.stdout.on('data', (data) => {
      for (const line of data.split(/\r?\n/)) {
        if (!line.trim()) continue;
        let message;
        try {
          message = JSON.parse(line);
        } catch {
          continue;
        }

        if (!message.id || !pending.has(message.id)) continue;
        const index = pending.get(message.id);
        pending.delete(message.id);
        results[index] = message;

        if (message.error) {
          finish(new Error(`codex app-server ${message.id} failed: ${JSON.stringify(message.error)}`));
          return;
        }

        if (message.id === 1) {
          child.stdin.write(`${JSON.stringify({ method: 'initialized', params: {} })}\n`);
          for (const request of requests) send(request.method, request.params);
        } else if (pending.size === 0) {
          finish(null);
        }
      }
    });

    child.stderr.setEncoding('utf8');
    child.stderr.on('data', (data) => {
      stderr += data;
    });

    child.on('error', finish);
    child.on('exit', (code) => {
      if (!settled && code !== 0) finish(new Error(`codex app-server exited with ${code}`));
    });

    send('initialize', {
      clientInfo: { name: 'ai-contexts-deploy', version: '1.0.0' },
      capabilities: { experimentalApi: true },
    });
  });
}

function uninstallCodexGlobals(targetDir, log = console.log) {
  let removed = 0;
  const contextsDir = path.join(targetDir, 'contexts');
  if (fs.existsSync(contextsDir) && fs.statSync(contextsDir).isDirectory()) {
    removePath(contextsDir);
    log('  DEL   contexts/');
    removed += 1;
  }
  const hooksDir = path.join(targetDir, 'hooks');
  if (fs.existsSync(hooksDir) && fs.statSync(hooksDir).isDirectory()) {
    removePath(hooksDir);
    log('  DEL   hooks/');
    removed += 1;
  }
  const hooksConfig = path.join(targetDir, 'hooks.json');
  if (fs.existsSync(hooksConfig) && fs.statSync(hooksConfig).isFile()) {
    removePath(hooksConfig);
    log('  DEL   hooks.json');
    removed += 1;
  }
  const agentsFile = path.join(targetDir, 'AGENTS.md');
  if (fs.existsSync(agentsFile) && fs.statSync(agentsFile).isFile()) {
    removePath(agentsFile);
    log('  DEL   AGENTS.md');
    removed += 1;
  }
  removed += uninstallSkills(targetDir, log);
  return removed;
}

function uninstallTarget(targetDir, options = {}) {
  const log = options.log ?? console.log;
  const removeAlias = options.removeAlias ?? true;
  let removed = 0;

  for (const category of [...CATEGORIES, ...LEGACY_CATEGORIES]) {
    const target = path.join(targetDir, category);
    if (fs.existsSync(target) && fs.statSync(target).isDirectory()) {
      removePath(target);
      log(`  DEL   ${category}/`);
      removed += 1;
    }
  }

  removed += uninstallSkills(targetDir, log);

  for (const entry of listEntries(sourceDir)) {
    if (!entry.isFile()) continue;
    if (SOURCE_ONLY_ROOT_FILES.has(entry.name)) continue;

    const target = path.join(targetDir, entry.name);
    if (fs.existsSync(target) && fs.statSync(target).isFile()) {
      removePath(target);
      log(`  DEL   ${entry.name}`);
      removed += 1;
    }
  }

  {
    const settings = targetDir === defaultGeminiDir() ? geminiSettingsObject() : claudeSettingsObject();
    const target = path.join(targetDir, 'settings.json');
    if (splitSettings(settings, target)) {
      log('  SPLIT settings.json');
      removed += 1;
    }
  }

  if (removeAlias) {
    unsetWtAddAlias(log);
  }

  return removed;
}

// 구버전에서 등록하던 글로벌 git wt-add alias를 제거한다. 워크트리 의존성 복구는
// 이제 PostToolUse self-heal hook(post-worktree-install / post-enterworktree-install)이
// 전담하므로 alias는 폐기한다. sync/unsync 모두에서 호출해 잔여 alias를 정리한다.
function unsetWtAddAlias(log = console.log) {
  const result = childProcess.spawnSync('git', ['config', '--global', '--unset', 'alias.wt-add'], {
    stdio: 'ignore',
  });
  if (result.error && result.error.code !== 'ENOENT') {
    throw result.error;
  }
  log('  OK   git wt-add 제거 완료');
}

module.exports = {
  CATEGORIES,
  SOURCE_ONLY_ROOT_FILES,
  baseSettingsSource,
  buildCodexAgentsContent,
  buildGeminiAgentsContent,
  claudeSettingsObject,
  codexHooksObject,
  geminiSettingsObject,
  comparePaths,
  copyPath,
  defaultCodexDir,
  defaultClaudeDir,
  defaultGeminiDir,
  deployCodexGlobals,
  deployGeminiGlobals,
  deployRootFiles,
  deploySkills,
  ensureDeploySource,
  ensureDir,
  listEntries,
  mergeSettings,
  readJson,
  readManagedKeys,
  removePath,
  unsetWtAddAlias,
  repoDir,
  resolveUserPath,
  settingsManifestPath,
  sourceDir,
  splitSettings,
  writeJson,
  trustCodexHooks,
  uninstallCodexGlobals,
  uninstallGeminiGlobals,
  uninstallTarget,
  verifyJsonExact,
  verifySettings,
};
